name: run-turuylevaade-daily

on:
  # 10:05 in Tallinn = 07:05 UTC
  schedule:
    - cron: '5 7 * * *'
  workflow_dispatch: {}          # manual “Run workflow” button

jobs:
  run:
    runs-on: ubuntu-latest

    # Set the minimal permissions required by the job
    permissions:
      contents: read            # checkout code
      id-token: write           # future-proof for OIDC, not used now

    steps:
      # 1 Pull the repo
      - uses: actions/checkout@v4

      # 2 Load the deployment key into an in-memory ssh-agent
      #    – nothing ever touches the runner’s disk
      - uses: webfactory/ssh-agent@v0.9.1      # pin exact tag
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 3 Trust the host fingerprint (prevents MITM & prompts)
      - name: Add server fingerprint
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # 4 Install R + binary packages
      - uses: r-lib/actions/setup-r@v2         # maintained by R-core / Posit
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::ssh,          # script does its own scp/ssh
            any::dplyr,
            any::tidyr,
            any::forcats,
            any::ggplot2,
            any::readr,
            any::stringr,
            any::lubridate,
            any::hrbrthemes,
            any::ggfittext,
            any::tidyquant,
            any::tseries,
            any::xts,
            any::plotly,
            any::ggalt,
            any::DT,
            any::jsonlite,
            any::rvest

      # 5 Fire the script (it uses SSH transparently via the agent)
      - name: Run R script
        run: Rscript run_turuylevaade.R
