# .github/workflows/docker-build.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'renv.lock'
  workflow_dispatch: {}

env:
  # See muutuja laheneb automaatselt väärtuseks 'iseppo/periodical'
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # --- UUENDATUD OSA ---
    # Logime sisse Docker Hubi, et vältida tõmbamislimiite ja autentimisvigu
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        # Jätame kasutajanime ja parooli tühjaks, et logida sisse anonüümselt
        # See on piisav avalike piltide jaoks
        registry: docker.io

    # See samm logib sisse GitHubi registrisse, et saaksime pildi sinna lükata
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max