# .github/workflows/docker-build.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Või master, olenevalt sinu peamisest harust
    paths:
      - 'Dockerfile'
      - 'renv.lock'
      - '.github/workflows/docker-build.yml' # Käivitub ka iseenda muutmisel
  workflow_dispatch: {} # Võimaldab manuaalset käivitamist

env:
  # See laheneb automaatselt väärtuseks 'iseppo/periodical'
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Vajalik pildi lükkamiseks GHCR-i

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Logime sisse Docker Hubi, et TÕMMATA baaspilti
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN2 }}

    # Logime sisse GitHubi, et LÜKATA valmis pilti
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Genereerime korrektsed sildid, mis sisaldavad ghcr.io aadressi
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.IMAGE_NAME }}

    # Ehitame pildi ja lükkame selle GHCR-i, kasutades eelnevalt genereeritud silte
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max